### ISSUE TITLE
Can't remotely subscribe with another PeerTube account

### ISSUE THREAD

**Issue by XenonFiber** [Chocobozzz/PeerTube#1693]
**What happened?**
Clicking "Remote subscribe" redirects to my instance with a "Sorry, but we couldn't find the page you were looking for" error. I'm doing this directly from the empty channel's page.

**What do you expect to happen instead?**
Remote subscription.

**Additional information**
* PeerTube version or URL: https://dialup.express
* Browser name/version: Firefox 65
* NodeJS version: v8.15.0

* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/):
https://pastebin.com/q7fHCy7B

**Comment by DeadSuperHero** [comment]
Thanks for filing a report! Just to be clear, are you trying to subscribe from your own PeerTube instance, or are you trying to do subscription from a different platform, such as Mastodon or Pleroma?

**Comment by XenonFiber** [comment]
@DeadSuperHero I'm trying to follow a channel on lostpod.space from lostpod.space with my dialup.express account.

**Comment by XenonFiber** [comment]
(Specifically because I can't do it from the channel page on dialup.express because it hasn't federated yet).

**Comment by DeadSuperHero** [comment]
Okay, cool. So, lostpod.space is a PeerTube instance (just so that we're on the same page)

So, this is definitely confusing, but I'm 99% sure that *Subscribe With a Remote Account* dialog is for platforms like Mastodon or Pleroma, which have a specific endpoint for remote following. It's definitely confusing, and the experience here could be way better.

As a workaround, I recommend copying and pasting the URL of the channel you want to follow in the search bar of your PeerTube instance. In other words, if you want to follow your Misc channel from dialup.express, you would copy this URL into lostpod.space's search form: https://dialup.express/video-channels/xenon_channel/

That will in turn pull the remote account details in, allowing you to subscribe from your lostpod.space account.

Let me know if you have any more questions about this!

**Comment by XenonFiber** [comment]
I think there's something weird going on with my instance then. I can see the account's page, but without any channels listed. If I try going directly to the channel, it can't be found.

Can channels without videos not federate?

**Comment by DeadSuperHero** [comment]
So, one other thing to be aware of: Accounts are not Channels. You'll need to specifically provide the channel URL (without /videos on the end) in the search form for the channel to show up in your search results.

> Can channels without videos not federate?

They should be able to by default!

**Comment by XenonFiber** [comment]
Ohhh, alright. I missed the "put it in the search bar" part. Thanks <3

**Comment by Chocobozzz** [comment]
Is it still an issue? Because I cannot reproduce with framapiaf.org and peertube3.cpy.re instances

**Comment by XenonFiber** [comment]
It's still an issue as described in the original post, but I managed to work around it.

**Comment by Chocobozzz** [comment]
What is your Mastodon instance version? And what is the URL of the page that PeerTube opens?

**Comment by XenonFiber** [comment]
Sorry, I meant that I can't remotely subscribe to a PeerTube channel on another PeerTube instance. It redirects to the "Not found" page.

**Comment by haelen** [comment]
I have the same problem with remote subscribe.

From here:

https://peertube.mastodon.host/videos/watch/a102285b-d790-44f0-a6c1-04100d4e364b

to here: https://mastodon.org.uk

Error message: "Unfortunately, there was an error looking up the remote account"

**Comment by Chocobozzz** [comment]
This should be fixed. See https://github.com/Chocobozzz/PeerTube/issues/1528#issuecomment-500328278

**Comment by virtadpt** [comment]
Still not working - can't subscribe to anything on feditube.com from video.hackers.town.  Tried everything in this ticket thread.

**Comment by Chocobozzz** [comment]
https://github.com/Chocobozzz/PeerTube/pull/3598
