### ISSUE TITLE
403 error when trying to follow peerTube user from pherephone

### ISSUE THREAD

**Issue by qwazix** [Chocobozzz/PeerTube#2197]
I am building [pherephone](https://github.com/writeas/pherephone) which is an *activityPub* repeater and I'm trying to make it work with as many AP implementations as possible.

**What happened?**
I am issuing the following follow request

``` yaml
Accept: application/activity+json; charset=utf-8
Accept-Charset: utf-8
Content-Type: application/activity+json; charset=utf-8
Date: Tue, 22 Oct 2019 07:36:32 GMT
Digest: SHA-256=K8g3os6T/GR0NOeMCS9yqc15eU5u2999Lr9DYJ9Jloo=
Host: pe.ertu.be
Signature: keyId="https://floorb.qwazix.com/myAwesomeList5#main-key",algorithm="rsa-sha256",headers="(request-target) date host digest",signature="OS0ydgE3fnM77csS4oNQj6XmD5+REsTgxk/24WMKsF5h5Qp3mWHdWH7EBVFfdy8AdC8sz5Oper8heK5dt8j+U1yaF8mM0uL2NlGncRtLsZxHUy2VtZy45XeuH9qgrMVSwTGqAHYDLlWBhPVO2SW5CJ+I/8ALpBLo8vr1BqwrbOZqV4eqwT87KrZm9PvzDJZVARRp1lMDPoeCo2cd9XT3kaGWyNL5Nhmi+uTJ9NIbcvtNY+RbcYljCs7ztC6RppEc5jEBOyvYK8xlQOg36ZZjH4ZknDMd0QacLkE9SYxagm916obZ9sDfMPD+HJjuOzwq5DfIT0gezQIxyDgxk8F85g=="
User-Agent: pherephone 0.99
```

``` json
 {
        "@context": [
                "https://www.w3.org/ns/activitystreams"
        ],
        "actor": "https://floorb.qwazix.com/myAwesomeList5",
        "id": "https://floorb.qwazix.com/myAwesomeList5/item/1YPm8w03xfTbfhtb",
        "object": "https://pe.ertu.be/accounts/qwazix",
        "type": "Follow"
} 
```

*PeerTube* responds with `403 Forbidden`

**What do you expect to happen instead?**

Return an `Accept` activity. Pixelfed, mastodon, writefreely and pleroma all accept these follow requests.

Any pointers on what PeerTube expects to be done differently?

**Comment by Chocobozzz** [comment]
Hi,

Could you provide me your tool or a curl command so I can test on a local instance? I could use curl but I'm not sure your body is indented exactly like your program sent to the peertube instance, so the digest could be invalid

**Comment by qwazix** [comment]
The tool is [pherephone](https://github.com/writeas/pherephone/tree/develop) 

You can find an x64 linux binary here: http://qwazix.com/shared/pherephone.zip

**Comment by Chocobozzz** [comment]
Thank you. It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/47581df0737ebcc058a5863143c752f9112a4424

peertube2.cpy.re should be updated in ~24 hours

**Comment by qwazix** [comment]
Thanks a lot!

**Comment by qwazix** [comment]
I'm still getting a 403 when trying to follow https://peertube2.cpy.re/accounts/root/

    POST request to https://peertube2.cpy.re/accounts/root/inbox failed (403): 403 Forbidden

(sorry for the big delay in testing this :-S)

**Comment by Chocobozzz** [comment]
Could you keep your server up so I can check the actor AP response?

**Comment by qwazix** [comment]
Yes, it's up and can leave it like this until you tell me otherwise.

**Comment by Chocobozzz** [comment]
I think the issue is that your `publicKeyPem` has `\\n` instead of `\n`:

```
{
  "@context": [
    "https://www.w3.org/ns/activitystreams"
  ],
  "followers": "https://floorb.qwazix.com/myAwesomeList5/peers/followers",
  "following": "https://floorb.qwazix.com/myAwesomeList5/peers/following",
  "id": "https://floorb.qwazix.com/myAwesomeList5",
  "inbox": "https://floorb.qwazix.com/myAwesomeList5/inbox",
  "name": "myAwesomeList5",
  "outbox": "https://floorb.qwazix.com/myAwesomeList5/outbox",
  "preferredUsername": "myAwesomeList5",
  "publicKey": {
    "id": "https://floorb.qwazix.com/myAwesomeList5#main-key",
    "owner": "https://floorb.qwazix.com/myAwesomeList5",
    "publicKeyPem": "-----BEGIN PUBLIC KEY-----\\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAp29sAx2gb74u2TaFK9Q3\\naLhXqkOI4CB5ocAg4D1W3W661I+zFsGBpd+KMdRfywXNy+5AmlHrCG+pnESQ5u2E\\ntP+gViksGpiIzgPW3s8fkDXbgC47sTuQItgocPgq0ymXLhD2k0zQHR6fZmBzOWq0\\nwYZ7Q2qKeF//cBPa+C36A9QkmlkBEtoON6KYgUfxrJ/JZh2N0QVMIDdLwJ9Ahpy9\\n5Rr6dZ9aeDYGfQId01Inx0XcdocOSJKpr1vEyvbim8ckC7GlRK/4rD5Ceh2IFLcZ\\n+RV7AUHWHSB5HJkNLshJJ52Bcri2asUKzQfuNOBDelt+H53JaSEbB2GWmMywA13e\\nxQIDAQAB\\n-----END PUBLIC KEY-----\\n"
  },
  "summary": "a list of favorite writers",
  "type": "Service"
}
```

**Comment by qwazix** [comment]
Yes, my bad. That was a side-effect of a change I did today. Sorry for bothering you with this.
