### ISSUE TITLE
when importing video from fakebook thumbnail url seems to long (255)

### ISSUE THREAD

**Issue by albjeremias** [Chocobozzz/PeerTube#2343]
**What happened?**

When i try to upload a file using a URL from facebook I get an error.. and peertube won't import the video. video: "https://www.facebook.com/ptrevolutiontv.live/videos/450177472587941/"

**What do you expect to happen instead?**
That the video is correctly imported ;) and that peertube would not fail to import the video, just because the import of the thumbnail failed.

**Steps to reproduce:**

1. Go to import video from URL

2. write this URL: https://www.facebook.com/ptrevolutiontv.live/videos/450177472587941/

3. continue the next steps

4. Go to Administration -> System -> Logs
Find the error why your video failed to import.

**Additional information**
* PeerTube version or URL: peertube - 2.0.0

* Link to browser console log if useful:
```error[12/16/2019, 7:09:31 PM] Cannot execute job 12 in queue video-import.{
  "payload": {
    "type": "youtube-dl",
    "videoImportId": 12,
    "thumbnailUrl": "https://scontent-frx5-1.xx.fbcdn.net/v/t15.5256-10/p200x200/75483142_450178619254493_3628944587105501184_n.jpg?_nc_cat=101&_nc_ohc=fj9zbb4XT_8AQkzmTEwzHvPq_gtm5LmrA9sdn2RPyY0Rqq3vX8S5dR2dg&_nc_ht=scontent-frx5-1.xx&oh=7e22daa8d2d723dac65264cc91c45946&oe=5E7566A1",
    "downloadThumbnail": true,
    "downloadPreview": true
  },
  "err": {
    "stack": "SequelizeDatabaseError: value too long for type character varying(255)\n at Query.formatError (/var/www/peertube/node_modules/sequelize/lib/dialects/postgres/query.js:366:16)\n at query.catch.err (/var/www/peertube/node_modules/sequelize/lib/dialects/postgres/query.js:72:18)\n at tryCatcher (/var/www/peertube/node_modules/bluebird/js/release/util.js:16:23)\n at Promise._settlePromiseFromHandler (/var/www/peertube/node_modules/bluebird/js/release/promise.js:547:31)\n at Promise._settlePromise (/var/www/peertube/node_modules/bluebird/js/release/promise.js:604:18)\n at Promise._settlePromise0 (/var/www/peertube/node_modules/bluebird/js/release/promise.js:649:10)\n at Promise._settlePromises (/var/www/peertube/node_modules/bluebird/js/release/promise.js:725:18)\n at _drainQueueStep (/var/www/peertube/node_modules/bluebird/js/release/async.js:93:12)\n at _drainQueue (/var/www/peertube/node_modules/bluebird/js/release/async.js:86:9)\n at Async._drainQueues (/var/www/peertube/node_modules/bluebird/js/release/async.js:102:5)\n at Immediate.Async.drainQueues [as _onImmediate] (/var/www/peertube/node_modules/bluebird/js/release/async.js:15:14)\n at runCallback (timers.js:705:18)\n at tryOnImmediate (timers.js:676:5)\n at processImmediate (timers.js:658:5)",
    "message": "value too long for type character varying(255)",
    "name": "SequelizeDatabaseError",
    "parent": {
      "stack": "error: value too long for type character varying(255)\n at Connection.parseE (/var/www/peertube/node_modules/pg/lib/connection.js:604:11)\n at Connection.parseMessage (/var/www/peertube/node_modules/pg/lib/connection.js:401:19)\n at Socket.<anonymous> (/var/www/peertube/node_modules/pg/lib/connection.js:121:22)\n at Socket.emit (events.js:198:13)\n at addChunk (_stream_readable.js:287:12)\n at readableAddChunk (_stream_readable.js:268:11)\n at Socket.Readable.push (_stream_readable.js:223:10)\n at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)",
      "message": "value too long for type character varying(255)",
      "name": "error",
      "length": 99,
      "severity": "ERROR",
      "code": "22001",
      "file": "varchar.c",
      "line": "624",
      "routine": "varchar",
      "sql": "INSERT INTO \"thumbnail\" (\"id\",\"filename\",\"height\",\"width\",\"type\",\"fileUrl\",\"automaticallyGenerated\",\"videoId\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,$1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *;",
      "parameters": [
        "9f19d3cf-f0ed-4bb7-b411-69f0e13d8e2c.jpg",
        122,
        223,
        1,
        "https://scontent-frx5-1.xx.fbcdn.net/v/t15.5256-10/p200x200/75483142_450178619254493_3628944587105501184_n.jpg?_nc_cat=101&_nc_ohc=fj9zbb4XT_8AQkzmTEwzHvPq_gtm5LmrA9sdn2RPyY0Rqq3vX8S5dR2dg&_nc_ht=scontent-frx5-1.xx&oh=7e22daa8d2d723dac65264cc91c45946&oe=5E7566A1",
        null,
        44460,
        "2019-12-16 19:09:31.658 +00:00",
        "2019-12-16 19:09:31.658 +00:00"
      ]
    },
    "sql": "INSERT INTO \"thumbnail\" (\"id\",\"filename\",\"height\",\"width\",\"type\",\"fileUrl\",\"automaticallyGenerated\",\"videoId\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,$1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *;"
  }
}
```

**Comment by Chocobozzz** [comment]
Thanks,  should be fixed in https://github.com/Chocobozzz/PeerTube/commit/2735a154dc77316e584bc784c65e904df791067f

**Comment by albjeremias** [comment]
I updated to lastest develop.. and still does not work.. 
`value too long for type character varying(255)`

you can try it yourself.. this is the video:
https://www.facebook.com/ptrevolutiontv.live/videos/440823149927597/
