### ISSUE TITLE
Import from Twitch is broken

### ISSUE THREAD

**Issue by mkody** [Chocobozzz/PeerTube#2860]
**What happened?**  
PeerTube can't import VODs from Twitch. I would get a HTTP 410 GONE with release 2.2.0.  

But a youtube-dl update was made on May 6th, so I tried using the latest develop-buster docker image and... I get a new error server-side.

Note: YouTube imports are working.

**What do you expect to happen instead?**
Video is added to the import queue.

**Steps to reproduce:**

1. Find a Twitch VOD (like <https://www.twitch.tv/videos/644940127>)

2. In PT, click "Upload" and then "Import from URL" and paste your URL

3. Click Import and wait as nothing happens for 2 minutes (I get a 500 then), but the error in the server logs appears as soon as the request is sent

**Additional information**
* PeerTube version or URL: 2.2.0 from chocobozzz/peertube:develop-buster (6/10/2020 at 5:37 am)
* Browser name/version: Chrome 83.0.4103.97
* NodeJS version: 10.21.0

* Link to browser console log if useful: -
* Link to server log if useful (journalctl or /var/www/peertube/storage/logs/): <https://gist.github.com/mkody/07a392ded833acf9e6ab3ec271b63e75>

**Comment by rigelk** [comment]
> But a youtube-dl update was made on May 6th

It doesn't not warrant all extractors are working. Notably, it seems youtube-dl has a broken Twitch extractor atm: github.com/ytdl-org/youtube-dl/pull/25606

**Comment by mat8913** [comment]
Individual VODs should be working in the latest youtube-dl. It's only entire channels (eg. `youtube-dl https://www.twitch.tv/rtsesport_tv/videos/past-broadcasts`) which are currently broken.

**Comment by mkody** [comment]
Oh I didn't see that PR. I saw this commit https://github.com/ytdl-org/youtube-dl/commit/ce3735df0270ef4dfd86a527c4d0edff822dd920 and the fact that the error now happens in `helpers/youtube-dl.js` and I get a 500 instead of a proper message like before (`{"error": "[...]"}`) made me believe there might be something peertube-wide to fix.

**Comment by rigelk** [comment]
@mat8913 thanks for pointing out the scope difference - let me reopen.

**Comment by Chocobozzz** [comment]
Thanks for the issue. Fixed in https://github.com/Chocobozzz/PeerTube/commit/c7763eddd14ee6a4a448d5187f46f79b22047d20

**Comment by mkody** [comment]
Just tried on latest develop and I'm still getting that error.

I guess there's something in `files` but nothing matches at line 69, so `matched` would be null.

**Comment by Chocobozzz** [comment]
Sorry. I fixed this in https://github.com/Chocobozzz/PeerTube/commit/982f2fc9b42537ca40ff29bf62c1ca3692d4b587
