### ISSUE TITLE
Tracker doesn't respect trust proxy settings

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#3580]
**Describe the current behavior**
While connecting to /tracker/socket the `trust_proxy` settings isn't working. Admin > System > Debug shows the correct client IP though. /tracker/socket route uses `proxy-addr` to get the client IP, while the routes that's working uses express built in (?) functions.

**Steps to reproduce:**

1. Put PeerTube behind a load balancer.
2. Watch a video.
3. Check the P2P functionality.

**Describe the expected behavior**
The client IP should be determined as is done in the other routes.

* PeerTube instance:
  * version: 3.0.0
  * NodeJS version: 12

* Browser name, version and platforms on which you could reproduce the bug:
Chrome
* Link to browser console log if relevant:
```
{"action":"announce","failure reason":"Unknown infoHash 57c0e31eadfb7143a309c5cdb66d7a41d01fabb1 requested by ip 10.1.0.187","info_hash":"WÀã\u001e­ûqC£\tÅÍ¶mzAÐ\u001f«±"}
```

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/b14e8e461f8f751e3d5927a20c7eb63b9ffa7a6a

**Comment by kontrollanten** [comment]
It still doesn't respect the trust proxy settings. The previous error is gone but now the proxy IP is getting blocked as soon as there's multiple simultaneous viewers. I get the `Blocking IP 10.0.1.27 from tracker` error. I also added a log message in the `TrackerServer` filter function to see the value of the `ip` variable, and it's value is the proxy IP.

**Comment by Chocobozzz** [comment]
It's weird, I can't reproduce and express uses the same `proxyAddr` function than us. And you still have the valid IP in the debug admin tab?

**Comment by kontrollanten** [comment]
Yes, it's still there. But in the filter function provided as an option to the TrackerServer there's no usage of `proxyAddr`, may that be the problem?

**Comment by Chocobozzz** [comment]
We send the ip to the filter function: https://github.com/Chocobozzz/PeerTube/blob/develop/server/controllers/tracker.ts#L94

**Comment by kontrollanten** [comment]
I just talked with my CDN provider and they confirmed that the problem lies on their side. Thanks for your help.
