### ISSUE TITLE
Livestream suddenly stops: Can't update video file since videoFile is undefined.

### ISSUE THREAD

**Issue by dabruh** [Chocobozzz/PeerTube#3682]
**Describe the current behavior**

The live stream stops after a seemingly random amount of time.

**Steps to reproduce:**

1. Start stream to tube.tchncs.de
2. Open stream in a _clean_ Firefox browser
3. Play the stream until it stops

**Describe the expected behavior**

Video should keep playing, or auto-resume.

**Additional information**

* PeerTube instance:
  * URL: https://tube.tchncs.de
  * version: 3.0.1
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug: Mozilla Firefox 85.0 (64-bit) for Manjaro Linux
* Link to browser console log if relevant: [console-export-2021-2-2_19-58-32.txt](https://github.com/Chocobozzz/PeerTube/files/5914449/console-export-2021-2-2_19-58-32.txt)
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by dabruh** [comment]
[console-export-2021-2-2_19-58-32.txt](https://github.com/Chocobozzz/PeerTube/files/5914449/console-export-2021-2-2_19-58-32.txt)

**Comment by Chocobozzz** [comment]
Hi,

I would need logs from the server.

**Comment by verymilan** [comment]
this just happened to me while switching back to the tab running the livestream. browserconsole stated a network error and then the videofile undefined error happened when i clicked play - it resulted in a black screen.
the only error from nginx for my ip (and somebody elses) would be `*67026284 pread() read only 0 of 553 from "/.../peertube/storage/streaming-playlists/hls/568c77d7-f132-415c-a062-d553a52563c4/0.m3u8" while sending response to client, client: <redacted>, server: tube.tchncs.de, request: "GET /static/streaming-playlists/hls/568c77d7-f132-415c-a062-d553a52563c4/0.m3u8 HTTP/2.0", host: "tube.tchncs.de", referrer: "https://tube.tchncs.de/"`

refreshing the site made it work again. 
i have not seen any failed jobs or other errors from the peertube log itself, matching this time.

**Comment by Chocobozzz** [comment]
@verymilan Do you have an `open_file_cache` directive in your nginx config?

**Comment by verymilan** [comment]
No... also i have just compared the config with the one from this repo, i am only missing some little things, like [`^/api/v1/(videos|video-playlists|users/me/avatar/pick)$`](https://github.com/Chocobozzz/PeerTube/blob/develop/support/nginx/peertube#L81) was outdated and only about avatars... and `proxy_ignore_client_abort on;` was missing. For the application, it's otherwise pretty much identical to the suggested config...

**Comment by Chocobozzz** [comment]
Okay thanks. I'll check if we can recover from a bad manifest error.

**Comment by Chocobozzz** [comment]
Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/2d056f6604ab6b5b8dd5ef35e936b89cc6fd48e6

**Comment by dabruh** [comment]
@Chocobozzz Issue is still appearing despite using v3.1.0 since 26th of March. See the interesting HTTP response at 19:24:17.192 which occurs just moments after the `HLS.js error: networkError - fatal: true - manifestParsingError` (@ 19:24:16.175). Console log: [console-export-2021-4-13_19-32-4.txt](https://github.com/Chocobozzz/PeerTube/files/6306267/console-export-2021-4-13_19-32-4.txt)

I can't really say I was doing anything in particular to provoke the manifestParsingError.

The stream started by itself after quite some time - I think because I managed to provoke `HLS.js error: mediaError - fatal: false - bufferStalledError` which appears to reload the stream. The bufferStalledError seems to happen when I switch tabs back and forth.

**Comment by alexeev-engineer** [comment]
i have errors.

```
Jan 28 18:11:17 2399731-ln68539.twc1.net peertube[9221]: [habratube.site:443] 2024-01-28 18:11:17.616 error: Client log: HLS.js error: networkError - fatal: true - manifestParsingError {
Jan 28 18:11:17 2399731-ln68539.twc1.net peertube[9221]:   "username": "alekseev",
Jan 28 18:11:17 2399731-ln68539.twc1.net peertube[9221]:   "userAgent": "Mozilla/5.0 (Linux; Android 10) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Mobile Safari/537.36",
Jan 28 18:11:17 2399731-ln68539.twc1.net peertube[9221]:   "url": "https://habratube.site/w/gFZUouJ6UBUfcuqNPtND2W"
Jan 28 18:11:17 2399731-ln68539.twc1.net peertube[9221]: }
```

how to fix this???
