### ISSUE TITLE
InvalidStateError: RTCPeerConnection is gone (did you enter Offline mode?)

### ISSUE THREAD

**Issue by kontrollanten** [Chocobozzz/PeerTube#3707]
**Describe the current behavior**
Our Sentry account got depleted due to thousands of `InvalidStateError: RTCPeerConnection is gone (did you enter Offline mode?)` errors from our clients. I guess the error itself is due to firewall or browser restrictions, but in average the users received ~80 errors each which looks like something is unhandled. 3,79% of the errors appears at /recently-added, the rest at video watch page.

**Steps to reproduce:**
I don't know how to reproduce.

**Describe the expected behavior**
The error should only be thrown once, if at all.

* PeerTube instance:
  * version: 3.0.1

* Browser name, version and platforms on which you could reproduce the bug:
All of the browsers are Firefox. Versions 81, 82, 84 and 85.
Platforms Ubuntu, Linux, Windows, MacOS.

**Comment by Chocobozzz** [comment]
Do you have the stacktrace of this error?

**Comment by kontrollanten** [comment]
Unfortunately not

**Comment by Chocobozzz** [comment]
See https://github.com/feross/simple-peer/pull/783

**Comment by Chocobozzz** [comment]
PR merged, fixed by https://github.com/Chocobozzz/PeerTube/commit/f9450247a8265033152412a1b98c86b48b802311

**Comment by cacious7** [comment]
I am still receiving this error on sentry. How do I resolve it, please? The error description is the same as this one.
