### ISSUE TITLE
Deleting privacy options breaks video uploading

### ISSUE THREAD

**Issue by michael-robbins** [Chocobozzz/PeerTube#4159]
**Describe the current behavior**
I've created a very basic plugin that all it does is this:
```
  registerHook({
    target: 'action:application.listening',
    handler: () => {
      videoPrivacyManager.deletePrivacy(1);
      videoPrivacyManager.deletePrivacy(2);
      videoPrivacyManager.deletePrivacy(3);
    }
  })
```

Context: I'd like a 'family' peertube which only Internal (4) videos can be uploaded.

In doing the above, the video upload page breaks in multiple ways, most commonly, I cannot publish videos as the Privacy dropdown isn't filled out/cannot be selected properly/results in blank dropdown.

**Steps to reproduce:**

1. Create a basic plugin, with just the above handler
2. Naviate to the 'Publish Video' page and observe the Privacy

<img width="1451" alt="Screen Shot 2021-06-04 at 11 08 35 pm" src="https://user-images.githubusercontent.com/1548818/120806110-cdddf900-c589-11eb-9f14-e080a363eb24.png">

**Describe the expected behavior**

I'd expect only 'Internal' is available to be selected, and the Dropdown box just contains that.

**Additional information**

* PeerTube instance:
  * URL: Private/internal
  * version: 3.2.1
  * NodeJS version: docker buster-production
  * Ffmpeg version: docker buster-production

* Browser name, version and platforms on which you could reproduce the bug: Firefox 89 Mac
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by michael-robbins** [comment]
Also it appears this deletion is permanent? Removing this plugin and restarting peertube still shows a broken video upload page

**Comment by rigelk** [comment]
> Also it appears this deletion is permanent? Removing this plugin and restarting peertube still shows a broken video upload page

Yes, the plugin modifies the database table associated with privacies.

**Comment by michael-robbins** [comment]
I think by deleting the Public privacy option, we break the frontend as the 'default' is no longer valid?

https://github.com/Chocobozzz/PeerTube/blob/9e2e51dc0bee5dc065a61c927e787ae021e8aa73/client/src/app/%2Bvideos/%2Bvideo-edit/video-add-components/video-upload.component.ts#L49

After making this change the API call to `/api/v1/videos/privacies` now only returns: `{"4":"Internal"}`

This seems to break within https://github.com/Chocobozzz/PeerTube/blob/fc21ef5c62d845576a916414468b3a57370a57b2/client/src/app/%2Bvideos/%2Bvideo-edit/video-add-components/video-send.ts#L46

I can see the privacy description set correctly by clicking on the privacies dropdown, but the 'label/name' of the privacy is blank. I think that might be because below that we're setting the default, which is hardcoded to PUBLIC?

**Comment by michael-robbins** [comment]
I think the frontend code should support receiving a limited set of privacy options and support any such combination provided.

**Comment by michael-robbins** [comment]
Leaving the privacy box 'untouched' and uploading a video results in the wrong privacy option (3, Private) being sent to the server, and the server correctly errors because it doesn't have that option available.

<img width="1696" alt="Screen Shot 2021-06-05 at 12 42 24 pm" src="https://user-images.githubusercontent.com/1548818/120877798-d66f1780-c5fb-11eb-955e-2ca79400c411.png">

**Comment by ferchuni** [comment]
I was able to reproduce this issue again with version `v3.3.0-rc.1 `

It seems like there is some strange behavior on UI.

It should show only `Unlisted` on privacy.

```
async function register ({
  videoPrivacyManager,
  playlistPrivacyManager
}) {
  videoPrivacyManager.deletePrivacy(1)
  videoPrivacyManager.deletePrivacy(3)
  videoPrivacyManager.deletePrivacy(4)
  playlistPrivacyManager.deletePlaylistPrivacy(1)
  playlistPrivacyManager.deletePlaylistPrivacy(3)
}

async function unregister () {
  return
}

module.exports = {
  register,
  unregister
}
```
![image](https://user-images.githubusercontent.com/1973207/124697562-5d463700-debd-11eb-9005-5cbbf3550328.png)

The upload process fails with `Incorrect request parameters: privacy` finally.

**Comment by Chocobozzz** [comment]
@ferchuni Thanks, the label should be fixed by https://github.com/Chocobozzz/PeerTube/commit/b980bcff7b6343d8c9747e735cb55645847e64da

**Comment by ferchuni** [comment]
@Chocobozzz  Thanks! The upload is still failing, but the label is ok now.

It is trying to send `"privacy": "3"` and the validation returns `"Should have correct video privacy"`

It should send `"privacy":"2"`  according to the plugin changes.

```
[localhost:9000] 2021-07-12 14:52:43.811 debug: Checking videosAddResumableInitValidator parameters and headers {
  "parameters": {
    "name": "file_example_MP4_480_1_5MG.mp4",
    "mimeType": "video/mp4",
    "size": "1570024",
    "lastModified": "1625521762818",
    "waitTranscoding": true,
    "commentsEnabled": true,
    "downloadEnabled": true,
    "channelId": 1,
    "nsfw": false,
    "privacy": "3",
    "filename": "file_example_MP4_480_1_5MG.mp4"
  },
  "headers": {
    "host": "localhost:9000",
    "connection": "keep-alive",
    "content-length": "1210",
    "pragma": "no-cache",
    "cache-control": "no-cache",
    "sec-ch-ua": "\" Not;A Brand\";v=\"99\", \"Google Chrome\";v=\"91\", \"Chromium\";v=\"91\"",
    "sec-ch-ua-mobile": "?0",
    "authorization": "Bearer 22b0fc9d5f84debbe51ab09aaa2f5fae3b08fe0e",
    "content-type": "multipart/form-data; boundary=----WebKitFormBoundarysX5iVTJ2U3BeMA6V",
    "accept": "application/json",
    "user-agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36",
    "x-upload-content-length": "1570024",
    "x-upload-content-type": "video/mp4",
    "origin": "http://localhost:9000",
    "sec-fetch-site": "same-origin",
    "sec-fetch-mode": "cors",
    "sec-fetch-dest": "empty",
    "referer": "http://localhost:9000/videos/upload",
    "accept-encoding": "gzip, deflate, br",
    "accept-language": "en-US,en;q=0.9"
  },
  "files": {}
}
[localhost:9000] 2021-07-12 14:52:43.825 warn: Incorrect request parameters {
  "path": "/api/v1/videos/upload-resumable",
  "err": {
    "privacy": {
      "value": "3",
      "msg": "Should have correct video privacy",
      "param": "privacy",
      "location": "body"
    }
  }
} 
```

**Comment by Chocobozzz** [comment]
Oup's, thanks. Please try https://github.com/Chocobozzz/PeerTube/commit/a3f45a2ab3cadf0946f06a0539993b828becd516

**Comment by ferchuni** [comment]
@Chocobozzz Thanks again, it works now, just two comments/bugs related to these changes.

* The `description` on the label is wrong. `"Unlisted"` has `"Only I can see this video"`
* After uploading a video but before publishing if you choose on privacy `"scheduled"` the upload fails.

The two cases here:

![image](https://user-images.githubusercontent.com/1973207/125651562-c701c754-acb0-420d-aca0-23dee5d81d11.png)

![image](https://user-images.githubusercontent.com/1973207/125651935-b6d974b5-ff3a-46ea-82e4-6e31d8400144.png)

![image](https://user-images.githubusercontent.com/1973207/125652137-a804b2e1-9ceb-4e37-a20d-551ed504fc3b.png)

**Comment by ferchuni** [comment]
@Chocobozzz Sorry to bother you. Is there any news about https://github.com/Chocobozzz/PeerTube/issues/4159#issuecomment-880009003 ? Thanks!

It happens using this plugin https://github.com/Chocobozzz/PeerTube/issues/4159#issuecomment-875254581

**Comment by Chocobozzz** [comment]
Sorry, I forgot your comment.

Descriptions are fixed by https://github.com/Chocobozzz/PeerTube/commit/d91714ca56f7baa2f0eff02f7c1ef2b891096171

Scheduled uploads need the private privacy so I think I'll just hide it

**Comment by ferchuni** [comment]
Great, thanks!. Yes, hiding `Scheduled` sounds good.

**Comment by Chocobozzz** [comment]
Done in https://github.com/Chocobozzz/PeerTube/commit/3ce48a0cd062d9ff64d9411d702453503a49f3b1
