### ISSUE TITLE
Embed Video URL is incorrect

### ISSUE THREAD

**Issue by Showfom** [Chocobozzz/PeerTube#4267]
**Describe the current behavior**

**Steps to reproduce:**

1. The video URL copied from embed video is https://peertube.cpy.re/videos/w/da2b08d4-a242-4170-b32a-4ec8cbdca701 which will return 404
2. The actual URL for PeerTube 3.3.0 should be https://peertube.cpy.re/w/sWxgbBUu1ScQkHqz831Qqi

**Describe the expected behavior**

**Additional information**

* PeerTube instance:
  * URL: All PeerTube
  * version: 3.3.0
  * NodeJS version: All
  * Ffmpeg version: All

* Browser name, version and platforms on which you could reproduce the bug: Tested from Firefox and Chrome

**Comment by Chocobozzz** [comment]
Thanks, should be fixed by https://github.com/Chocobozzz/PeerTube/commit/a66424978c681af87aaee92ce6d2ca600d79b82c

**Comment by Showfom** [comment]
Still not fixed on 3.3.0-nightly-2021-07-28

Example

https://peertube2.cpy.re/videos/embed/264ff760-803e-430e-8d81-15648e904183

![image](https://user-images.githubusercontent.com/6773591/127405140-8ecedf72-fa02-4662-bea7-0be64668574b.png)

When click the PeerTube button, it will redirect to https://peertube2.cpy.re/w/undefined

`Copy the Video URL` has been fixed

**Comment by Chocobozzz** [comment]
Oup's https://github.com/Chocobozzz/PeerTube/commit/88d36fe4dcd45f410f52de67c9299ad9b00c0b4e
