### ISSUE TITLE
Advanced filter error after upgrade

### ISSUE THREAD

**Issue by Alterak** [Chocobozzz/PeerTube#4365]
**Describe the current behavior**

I have updated my instance to version 3.4.0-rc.1. I am trying to use the advanced filter. I have nothing installed by default. When I install any filter, an error appears, and nothing changes.
I use the Russian interface language.
I tried to change the interface language to English - in this case everything works correctly.

This is a screenshot when the interface language is English.
![Screenshot_1](https://user-images.githubusercontent.com/11453567/131464021-45c72b4c-3b10-4d73-b9d9-7afb39f0052f.png)

This is a screenshot when the Russian interface language is selected.
![Screenshot_2](https://user-images.githubusercontent.com/11453567/131464056-b91ba3d6-f7b2-423d-a19e-73ec46e71975.png)

**Steps to reproduce:**

1. Open the Trends page, or Recently added.
2. Make more filters and try to change any field.
3. We get the error "Can't download more videos. Please try again later".

**Describe the expected behavior**

The filter should work correctly even if a different interface language is selected. (in my case Russian language)

* PeerTube instance:
  * URL: https://peervideo.ru
  * version: 3.4.0-rc.1
  * NodeJS version: v12.22.2
  * Ffmpeg version: 4.1.6-1~deb10u1

**Comment by Alterak** [comment]
On the test server, I tried to install the nightly build version 3.3.0-nightly-2021-08-31. In this version, the advanced filter uses English, so everything works correctly and correctly.
I assume that there are errors in the translations of the Russian language.

**Comment by Alterak** [comment]
I just noticed that if you log in as "Guest", then all confidential content is displayed, even if the default "Hide" is selected in the server settings. Big request, fix this error as soon as possible!

**Comment by Alterak** [comment]
Unfortunately I had to downgrade the version again to 3.3.0 - (

**Comment by Chocobozzz** [comment]
Fixed by https://github.com/Chocobozzz/PeerTube/commit/6d210220be0875d63461829d83c6e3a59d05cf7a

**Comment by Alterak** [comment]
> Fixed by [6d21022](https://github.com/Chocobozzz/PeerTube/commit/6d210220be0875d63461829d83c6e3a59d05cf7a)

In nightly build 3.4.0-rc.1-nightly-2021-09-08, the filter still doesn't work. Especially the confidential content function.

**Comment by Chocobozzz** [comment]
> the filter still doesn't work. Especially the confidential content function.

I don't understand. Could you explain what doesn't work?

>  Also in the default settings there is no Category and Language. And there is no way to select All available categories and languages

These fields are just an information of main languages spoken by instance admins/moderators and main instance topics. They don't automatically filter videos.

**Comment by Alterak** [comment]
> I don't understand. Could you explain what doesn't work?

I showed it again in the video. Look at this please. https://video.ustim.ru/w/kRS9S88yqG4yc7wCR7LSmm
When I have selected the Russian interface language, the "Type" and "Sensitive content" functions do not work
When I choose English for the interface, these functions work fine.


> These fields are just an information of main languages spoken by instance admins/moderators and main instance topics. They don't automatically filter videos.

On these functions, I myself was mistaken. Everything is alright with them. Sorry-)

**Comment by Chocobozzz** [comment]
Thanks! Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/8a7abfef88b5fc69f8809dcbb511e923597a0163

**Comment by Alterak** [comment]
> Thanks! Should be fixed by [8a7abfe](https://github.com/Chocobozzz/PeerTube/commit/8a7abfef88b5fc69f8809dcbb511e923597a0163)

Thanks. I installed build 3.4.0-rc.1-nightly-2021-09-09 today. Everything works perfectly! You are cool!
