### ISSUE TITLE
Peertube-import-videos.js - Only downloads in 720p

### ISSUE THREAD

**Issue by ghost** [Chocobozzz/PeerTube#4949]
**Describe the current behavior**
When using peertube-import-videos.js to import videos from YouTube, is only downloads them in 720p.

If I upload a video with "Import with URL" on the instance, it downloads the highest resolution available.

The instance allows 1440p, 1080p and 720p.

_dist/server/helpers/youtube-dl/youtube-dl-cli.js_
> const resolution = enabledResolutions.length === 0
>  ? **720**
>  : Math.max(...enabledResolutions);

Changing **720** to **1080** will make it download up to 1080p, but changing it to **1440** or **2160**, does not work.

**Steps to reproduce:**

1. Run peertube-import-videos.js
2. Will only download the video in 720p

**Describe the expected behavior**
It is supposed to download the best quality and convert it to the resolutions allowed on the instance.

**Additional information**

* PeerTube instance:
  * version: 4.1.1
  * NodeJS version: 14
  * Ffmpeg version: 4.2.4-1ubuntu0.1

**Comment by WonderingDane** [comment]
Another thing only impacting the script: Really slow download speeds. Around 64Kbit/s... This is not the case when downloading a youtube video with the PeerTube interface.

**Comment by SimplyCorbett** [comment]
I can confirm this bug.

Re: slow download speeds - you're going to have to remove youtube-dl in the installation you're running the import script and replace it with yt-dlp, then rename yt-dlp to youtube-dl. That fixes my slow speed.

**Comment by WonderingDane** [comment]
> 

Not sure how to do that.
I use the remote tools: https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/tools.md

**Comment by SimplyCorbett** [comment]
> > 
> 
> Not sure how to do that.

Where you installed cli tools. In my case peertube-temp.

```
root@video:/var/www/peertube-temp# node dist/server/tools/peertube-import-videos.js -u url -U "anonymous" --password "password" --target-url url
[localhost:9000] 2022-05-16 18:30:33.581 info: Updating youtubeDL binary from https://yt-dl.org/downloads/latest/youtube-dl.
[localhost:9000] 2022-05-16 18:30:37.030 info: youtube-dl updated /var/www/peertube-temp/storage/bin/youtube-dl.
```

```
cd /var/www/peertube-temp/storage/bin
rm youtube-dl
wget https://github.com/yt-dlp/yt-dlp/releases/download/2022.04.08/yt-dlp
mv yt-dlp youtube-dl
```

done

**Comment by vincib** [comment]
Hi.

This bug is still present in latest (head of git as of today = commit bb7e5605d15a2e58791b08101a77fe3437c111a5 ) CLI tools. 

I confirm that if you change dist/server/helpers/youtube-dl/youtube-dl-cli.js line 65 the  "? 720" by a "? 1080" this will enable 1080p download from YT.

So if you want to be able to import from YT to PT with at least 1080p, maybe this patch could be proposed as a PR?

**Comment by vincib** [comment]
> Another thing only impacting the script: Really slow download speeds. Around 64Kbit/s... This is not the case when downloading a youtube video with the PeerTube interface.

This is not the case anymore (at least from here) if you update YT-DLP to latest version. Some time in 2022, the youtube-dl & yt-dlp code were not able to download fast from YT. That's solved now, but you NEED to update your yt-dlp in storage/bin/

**Comment by MatKurianski** [comment]
Hey, I have an interest in working on this change, but before it, I want to clarify what the intended behavior is. If I understood right, the ideal behavior should be:

1. Request the instance enabledResolutions (not sure how to do that yet)
2. Download the video from Youtube matching the maximum resolution enabled by the instance
3. Upload it to Peertube

Did I understand it right? I am still not familiar with Peertube, and I intend to learn more about the software while I learn more about the code, so I would be glad if someone could point me any misunderstanding.

**Comment by vincib** [comment]
yess, this seems like a very good and precise idea
