### ISSUE TITLE
Support for draft 11 of HTTP signatures

### ISSUE THREAD

**Issue by Nutomic** [Chocobozzz/PeerTube#4963]
I just finished implementing support for federation with Peertube in [Lemmy](https://join-lemmy.org/). This was mostly straightforward, but there is one important problem. When sending any activity to Peertube, it responds with the following error:

`Send https://ds9.lemmy.ml/activities/create/24762c6a-741f-43c7-b347-80e504f25c61 to https://framatube.org/inbox failed with status 403 Forbidden: {"type":"about:blank","title":"Forbidden","detail":"date was not a signed header","status":403,"error":"date was not a signed header"}`

The problem is most likely because you only support older drafts of the http-signatures standard which still use the `date` header. Lemmy instead signs using [draft 11](https://datatracker.ietf.org/doc/html/draft-cavage-http-signatures-11), which uses fields `(created)` and `(expires)` instead of `date`. We already federate with a lot of projects like this, so it would be great if Peertube could also support verification of draft 11 signatures. Note that Lemmy can receive older http signatures using date without problem, so there is no need to change your sending code.

For reference, this is what the signature related headers sent by Lemmy look like:
```
"content-type": "application/activity+json",
"host": "framatube.org",
"digest": "SHA-256=WjWuzIro71uSt+mU9GVDSjaugXRCOQrm9eIP5pvtlSc=",
"signature": "keyId=\"https://ds9.lemmy.ml/u/nutomic#main-key\",algorithm=\"hs2019\",created=\"1651837468\",expires=\"1651837478\",headers=\"(request-target) (created) (expires) content-type digest host\",signature=\"MrYw0y7k/O5KMYr/6yQm8NKEa6shdqKeKUT3Og0+L6e3NdONzIMh8CL5jVlQfjCUQ+bnhJyPQASlL71Rq7hzqNVEsfhUwFCRTHD8aX/HijbeYcbOrRSlNZ7JgdAuR4z90frprRt2Cip3/Einwmf0i9BsgwG0u1yGMOpoYukNckhmGByvzX7PwchBpwCRBi6TrML8piEhIo8HJtVKo1k9wg9MTpa74s9zRbgcFL4ZK1DrwgI/lSuKsQO22cUvlg/u0YA9R/2qddg8Bs18P4jEAbp0Gw3n0eogVuyWAroDDGopWQ8pP5M6+/3OmizSZpXkPNxmDhKICp7PVc7EcOwG9w==\"",
```

By the way, here you can see a Peertube video and channel in Lemmy: https://ds9.lemmy.ml/post/26527

**Comment by Chocobozzz** [comment]
Hi, thanks this is great!

I added support for draft 11 in https://github.com/Chocobozzz/PeerTube/commit/e08ec7a723724c247d9bbcdbf157da08d3ba31a7

The commit will be released in nightly tomorrow, and you'll be able to test on https://peertube2.cpy.re/ on monday

**Comment by Nutomic** [comment]
That was fast, thank you!

**Comment by Nutomic** [comment]
I'm still getting the same  error as before:

`
WARN background_jobs_core::processor_map: Job errored: Processing(Send https://ds9.lemmy.ml/activities/follow/c58a8347-d65c-4a77-b537-455586ea853d to https://peertube2.cpy.re/video-channels/vijay_channel/inbox failed with status 403 Forbidden: {"type":"about:blank","title":"Forbidden","detail":"Invalid signature","status":403,"actorUrl":"https://ds9.lemmy.ml/u/nutomic","error":"Invalid signature"})
`

**Comment by Chocobozzz** [comment]
I think it's related to this discussion: https://github.com/misskey-dev/misskey/issues/8165#issuecomment-1120943949

PeerTube uses sha-512 where Mastodon and Lemmy chose sha-256 when using `hs2019`. I think I'll switch to sha-256.

**Comment by Nutomic** [comment]
Tried again, this time it worked and i got an Accept back. A [comment](https://peertube2.cpy.re/w/2QLnpdPPQwVoe5HZVzvMWU) also went through from Lemmy to Peertube. Even nested comments federate correctly between different Lemmy instances in a Peertube group, great! 

In general, i have added test cases for parsing Peertube `Group`, `Video`, `Person`, `Note` and `Announce/Video`, so those should all work fine. Is there anything else worth testing, maybe vote or delete activities?

I will also have to wait for some video to be published, to see that its received correctly (but as comments work, i dont expect problems here).

**Comment by Nutomic** [comment]
I have received some reports that federation between Peertube and Lemmy is still not working correctly, and after testing I can confirm this. Both framatube.org and peertube2.cpy.re sometimes respond to follow requests with:

`Processing(Send https://ds9.lemmy.ml/activities/follow/a7e713e1-bf2c-45f2-8c7e-a0b243bbd469 to https://peertube2.cpy.re/inbox failed with status 403 Forbidden: {"type":"about:blank","title":"Forbidden","detail":"Invalid signature","status":403,"actorUrl":"https://ds9.lemmy.ml/u/nutomic","error":"Invalid signature"})`

Other times, no HTTP response is logged at all. Whats strange is that comments go through sometimes (but not always).

I will send an email with login info for ds9.lemmy.ml for testing. Let me know if i should open a new issue.

**Comment by Chocobozzz** [comment]
Thanks @Nutomic

It seems there is a timing issue when PeerTube signs HTTP requests. It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/319f9670bfd07f19862de565c7cc936ba7f6fda9 and available on peertube2 on monday.

Regarding your 403 error, it seems caused by an outdated public key in peertube database for your account. PeerTube refreshes actors after 2 days so I suggest to do another test in the week-end.

**Comment by Nutomic** [comment]
It still doesnt seem to work, Peertube simply doesnt send an accept back. However, i got lucky a single time where it worked correctly.
