### ISSUE TITLE
Page view count federation / summing

### ISSUE THREAD

**Issue by yassinphilip** [Chocobozzz/PeerTube#548]
The page view count seems to be broken, consider this video : 

On its original instance, the view count for [this video](https://exode.me/videos/watch/150e8685-b7ce-4cdc-92b9-8ac25c2cdec0) is 228.
On all other federated instances, the view count is seriously different:
[On mastodon.host](https://peertube.mastodon.host/videos/watch/150e8685-b7ce-4cdc-92b9-8ac25c2cdec0), **141** views
[On peertube.nsa.ovh](https://peertube.nsa.ovh/videos/watch/150e8685-b7ce-4cdc-92b9-8ac25c2cdec0), **138** views :(

It's different on every instance, and it _stays_ different, I have waited weeks for some sort of synchronization, but it has not occured yet.

**Comment by Chocobozzz** [comment]
Some brodcast jobs got stuck. I tried to fix that https://github.com/Chocobozzz/PeerTube/commit/71e3dfda4e2bcc228415c0d66b09a84bb73dddd1

**Comment by Zig-03** [comment]
> Some brodcast jobs got stuck. I tried to fix that [71e3dfd](https://github.com/Chocobozzz/PeerTube/commit/71e3dfda4e2bcc228415c0d66b09a84bb73dddd1)

Not sure it got fixed. Take a look at the view numbers of these videos on two different instances:
https://peertube2.cpy.re/accounts/blender@video.blender.org/videos
https://video.blender.org/

**Comment by BO41** [comment]
@Chocobozzz just fixed a problem like this in the newest develop. I think here: 030177d246834fdba89be9bbaeac497589b47102 .
So after the next release this should be fixed, AFAIK

**Comment by Zig-03** [comment]
@Chocobozzz It seems like this bug isn't fixed as mentioned in v1.1.0-rc.1 release notes 

> Fix video views inconsistencies inside the federation

For example, both of these instances run on v1.1.0-rc.1, yet this video has a different number of views
228 views - https://peertube.social/videos/watch/f9237f0f-3c73-4bfe-a99c-ace1c2e25dd8
148 views - https://peertube2.cpy.re/videos/watch/f9237f0f-3c73-4bfe-a99c-ace1c2e25dd8
234 views - https://peertube3.cpy.re/videos/watch/f9237f0f-3c73-4bfe-a99c-ace1c2e25dd8

**Comment by Chocobozzz** [comment]
The upgrade must be done on the origin server, so https://share.tube/about/instance
