### ISSUE TITLE
Live streaming buffering frequently 

### ISSUE THREAD

**Issue by upcastvideo** [Chocobozzz/PeerTube#5681]
### Describe the current behavior

I installed a peertube instance in a dedicated CPU droplet with 16GB RAM and 8 CPU´s. I`m testing live streaming with several transcoding resolutions with low latency. So far using my iphone live streaming goes smoothly, but trying with my computer the video gets buffered often, so after a few minutes the lag between the real time streaming and the video player is big. 

I asked a few friends, and all of them have the same issue. Is not a computer CPU power issue, I tried with a couple of brand new macbook pro.

I´m planing to have a chat for live streaming as well, so low latency 10-15 seconds will be great. 30 seconds delay makes interactivity with users worst since they are expecting you to see people messages and answer it fast.

### Steps to reproduce

1. Install peertube through docker in DO
2. Initiate live streaming with low latency and 3 resolutions.
3. Watch live streaming in another computer. Video gets buffered often.

### Describe the expected behavior

I expect the live streaming to be reproduced smoothly, since the server I have is big enough in both CPU and bandwidth.

### Additional information

* PeerTube instance:
  * URL:
  * Version:
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by vid-bin** [comment]
Please provide the output of the following command:

cat /proc/cpuinfo | grep "model name"

If you are running multiple live encodes (480p, 720p and 1080p) you will likely need more then 8 cores.

**Comment by upcastvideo** [comment]
model name	: Intel(R) Xeon(R) Platinum 8358 CPU @ 2.60GHz
model name	: Intel(R) Xeon(R) Platinum 8358 CPU @ 2.60GHz
model name	: Intel(R) Xeon(R) Platinum 8358 CPU @ 2.60GHz
model name	: Intel(R) Xeon(R) Platinum 8358 CPU @ 2.60GHz
model name	: Intel(R) Xeon(R) Platinum 8358 CPU @ 2.60GHz
model name	: Intel(R) Xeon(R) Platinum 8358 CPU @ 2.60GHz
model name	: Intel(R) Xeon(R) Platinum 8358 CPU @ 2.60GHz
model name	: Intel(R) Xeon(R) Platinum 8358 CPU @ 2.60GHz

**Comment by upcastvideo** [comment]
I´m running live streaming only with 720p. I tried now with the default latency mode and now it works well, but the delay is 30 seconds.

**Comment by Chocobozzz** [comment]
Thanks! The issue should be fixed by https://github.com/Chocobozzz/PeerTube/commit/f967d8be4dd7bc806d9b9c2d848cdadbe6752c16

**Comment by upcastvideo** [comment]
Hello, the problem is not solved yet. With default latency mode there is not buffering, but with low latency there is buffering. I need to stream at low latency since we are going to have a live chat. Any ideas? Thanks.

**Comment by upcastvideo** [comment]
I just tried again live streaming at default latency mode, and there something interesting. In my phone delay is about 20 seconds while in my laptop delay is 30 seconds.

I´m using Iphone 12 pro and a Macbook pro M2 (not the one where I´m streaming from).

**Comment by Chocobozzz** [comment]
> I´m not sure if you are implementing this changes to fix the low latency mode in the next Peertube update?

It will be included in 5.1 stable, in 1 or 2 weeks

**Comment by upcastvideo** [comment]
Great thanks
