### ISSUE TITLE
S3 download fails when the filename contains `(` or `:`

### ISSUE THREAD

**Issue by pat971** [Chocobozzz/PeerTube#6161]
### Describe the current behavior

Hello,
Before opening this issue I followed this #6117 

In my case, when the filename contains `(` or `:` I get an error 

`InvalidRequest invalid b2-content-disposition: expected a token character at 27, but got ':'` 

or 

`InvalidRequest invalid b2-content-disposition: expected a token character at 38, but got '('`

### Steps to reproduce

1. Use object storage (Back Blaze in my case)
2. Upload a video with a title containing `(` or `:`
3. Click the Download button

### Describe the expected behavior

The video resource should be retrieved properly from S3

### Additional information

  * PeerTube Version: 6.0.2
  * NodeJS version: v18.19.0

**Comment by Chocobozzz** [comment]
Hi,

Thanks, it should already be fixed by https://github.com/Chocobozzz/PeerTube/commit/c93b7088c2a6bffd0cec24909797bde4cb6095b8 (will be available in peertube 6.1)

**Comment by pat971** [comment]
> Hi,
> 
> Thanks, it should already be fixed by [c93b708](https://github.com/Chocobozzz/PeerTube/commit/c93b7088c2a6bffd0cec24909797bde4cb6095b8) (will be available in peertube 6.1)

However, I've made these changes and restarted PeerTube, but the problem persists.

**Comment by Chocobozzz** [comment]
Can you provide the URL of the video so I can reproduce on your instance?

**Comment by pat971** [comment]
> Can you provide the URL of the video so I can reproduce on your instance?

Yes, try with this one for the `:`

https://gade.o-k-i.net/w/ozwLsFdpMu5hDTAx4XKyJb

And this one for the `(`

https://gade.o-k-i.net/w/ns15e4h2H2A5fCdki2qL24

**Comment by Chocobozzz** [comment]
Can you try to add `"` to `filename` value in the patch?

```
`attachment; filename="${encodeURI(downloadFilename)}"`
```

**Comment by pat971** [comment]
> Can you try to add `"` to `filename` value in the patch?
> 
> ```
> `attachment; filename="${encodeURI(downloadFilename)}"`
> ```

Thank you :pray: , it works with this patch 😊
