### ISSUE TITLE
Video views always 0

### ISSUE THREAD

**Issue by rorizhang** [Chocobozzz/PeerTube#6307]
### Describe the current behavior

Video views always 0

### Steps to reproduce

1.install docker
2.install nginx proxy manager by docker
3.install peertube by docker
[docker-compose.yml]
services:

  postgres:
    image: postgres:13-alpine
    env_file:
      - .env
    volumes:
      - ./db:/var/lib/postgresql/data
    restart: "always"

  redis:
    image: redis:6-alpine
    volumes:
      - ./redis:/data
    restart: "always"

  peertube:
    image: chocobozzz/peertube:production-bookworm
    env_file:
      - .env
    ports:
      # - "1935:1935" # Comment if you don't want to use the live feature
      - "20115:9000" # Uncomment if you use another webserver/proxy or test PeerTube in local, otherwise not suitable for production
    volumes:
      - ./data:/data
      - ./config:/config
    depends_on:
      - postgres
      - redis
    restart: "always"

[.env]
POSTGRES_PASSWORD=XXX

POSTGRES_DB=peertube

PEERTUBE_DB_USERNAME=$POSTGRES_USER
PEERTUBE_DB_PASSWORD=$POSTGRES_PASSWORD
PEERTUBE_DB_SSL=false

PEERTUBE_DB_HOSTNAME=postgres

PEERTUBE_WEBSERVER_HOSTNAME=XXX

PEERTUBE_TRUST_PROXY=["127.0.0.1", "loopback", "uniquelocal", "172.26.0.1"]

PEERTUBE_SECRET=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

PEERTUBE_SMTP_USERNAME=XXX
PEERTUBE_SMTP_PASSWORD=XXX

PEERTUBE_SMTP_HOSTNAME=XXX
PEERTUBE_SMTP_PORT=XXX
PEERTUBE_SMTP_FROM=XXX
PEERTUBE_SMTP_TLS=true
PEERTUBE_SMTP_DISABLE_STARTTLS=true
PEERTUBE_ADMIN_EMAIL=XXX

PEERTUBE_OBJECT_STORAGE_UPLOAD_ACL_PUBLIC="public-read"
PEERTUBE_OBJECT_STORAGE_UPLOAD_ACL_PRIVATE="private"

### Describe the expected behavior

Why and how to resolve?

### Additional information

This instance is deployed in a closed intranet environment. Should I pay attention to something?
CentOS 7.9
Docker Engine 26.0.0
Nginx Proxy Mnanger 2.10.4
Peertube pulled the latest by now

**Comment by Chocobozzz** [comment]
Hi,

Views are buffered so you may notice a delay before the counter is actually updated

**Comment by rorizhang** [comment]
I played all night. But it is still 0.

**Comment by Chocobozzz** [comment]
Can you enable peertube debug logs and paste them?

**Comment by rorizhang** [comment]
Would you please tell me how to enable it in docker mode?在 2024年4月2日，17:33，Chocobozzz ***@***.***> 写道：﻿
Can you enable peertube debug logs and paste them?

**Comment by rorizhang** [comment]
[error_log.txt](https://github.com/Chocobozzz/PeerTube/files/14835125/error_log.txt)
Is it?

**Comment by Chocobozzz** [comment]
Thanks, the issue should be fixed by https://github.com/Chocobozzz/PeerTube/commit/f8b8dc674e9aec5a8b91357304541fc511284700

You can set `geo_ip.enabled` to `false` (https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example#L397) as a workaround until the next peertube version is released

**Comment by rorizhang** [comment]
I updated the latest docker image(chocobozzz/peertube:production-bookworm,image id:6ff1e77db6a1) yesterday, but the problem is still as it was.  Could you please give the release plan? Thank you so much.

**Comment by rorizhang** [comment]
> I updated the latest docker image(chocobozzz/peertube:production-bookworm,image id:6ff1e77db6a1) yesterday, but the problem is still as it was. Could you please give the release plan? Thank you so much.
