### ISSUE TITLE
Error Post Live - saving replay

### ISSUE THREAD

**Issue by stevespaw** [Chocobozzz/PeerTube#6651]
### Describe the current behavior

After a live stream - we continually have errors after upgrade to 6.3.1
The "Live video ending" seems to stayed delayed for a long period, and then it fails. 
The saved videos sit in "waiting to transcode state and never move to Object storage
No Thumbnail is created

new split audio option seems to have no effect ether way on this issue

This is a real Blocker for us ! I have been pulling my hair out.

### Steps to reproduce

1. Stream to a permanent live - save replay. (No transcodes on live)
2. Live video seems to be fine
3. Stop video
4. Log view says "live video ending" delayed for a long period of time
5.Eventually it says fails and the video with now thumbnail appears

![image](https://github.com/user-attachments/assets/b5501113-62f6-4bb6-9f78-9dd64b39a14e)
![image](https://github.com/user-attachments/assets/cf8fc598-5f76-4f8e-b2c6-4eb9d16ad1fd)

6.

### Describe the expected behavior

to go live and when complete move the file and thumbnail/preview to object storage.

### Additional information

* PeerTube instance:
  * URL:
  * Version: 6.3.1
  * NodeJS version:
  * Ffmpeg version:

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by kntndrsn** [comment]
Just to echo. I have the same issue. The workaround has been to manually set the thumbnail and either restart the transcode or manually update the status in the database.

**Comment by kntndrsn** [comment]
I figured out why it's doing this. Replays are now being saved with the thumbnail from the Live. For my existing permanent/recurring live configurations the thumbnail was not populated in the preview folder. This was causing the error to be thrown when the live ended.

All I had to do was reapply the thumbnail for the recurring live configuration and it started working.

Hope this helps.

**Comment by Chocobozzz** [comment]
Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/ef8e5cad585cfb3a4356ca15fe8485f9fbed0519

But I think there's something wrong with your live, it should have a default thumbnail :thinking: (don't hesitate to provide a link to the live so I can check)

**Comment by stevespaw** [comment]
@kntndrsn @Chocobozzz I have tried reapplying the thumbnail, and that does not fix this for us.

**Comment by stevespaw** [comment]
It seems that this may be connected to the thumbnail, we usually created a new poster image, but just creating a new live with the default "peertube" image has the same problem post live.

**Comment by stevespaw** [comment]
Another hint  - "some" previously created live with custom images do still work, but the resulting replay has the thumbnail if the uploaded image on the "live" that was created. So this seems to be a different behavior . What is the intended output of replay? To have the thumbnail of the "live" or an image created from the stream?

**Comment by stevespaw** [comment]
6.3.2 seems to have resolved this! Thank you @Chocobozzz
