### ISSUE TITLE
Preview image file removed for  Live when replay thumbnail updated

### ISSUE THREAD

**Issue by kntndrsn** [Chocobozzz/PeerTube#6673]
### Describe the current behavior

When a replay of a permanent live is saved, it references the preview image of the live. If you change the thumbnail on the replay, it appears to remove the preview image file of the live.

Example Live: https://video.bbccolumbus.com/w/wT9mi5VQ3N2RHTrQ87TjqN

![image](https://github.com/user-attachments/assets/07f683fe-b397-4d34-9b63-f48ec23b07e3)

### Steps to reproduce

1. Setup live with a custom thumbnail image.
2. Initiate live and finish to create replay.
3. Change thumbnail on replay.
4. Original live preview image file will be gone. (thumbnail image file will still be there)

### Describe the expected behavior

1. Previous to 6.3, replays would generate their own thumbnail and preview images. However, at a minimum, it shouldn't delete the preview image file of the original live when you change the thumbnail of a replay.

### Additional information

* PeerTube instance:
  * URL: 
  * Version: 6.3.2
  * NodeJS version: 21.7.3
  * Ffmpeg version: 4.4.2-0ubuntu0.22.04.1

* Browser name, version and platforms on which you could reproduce the bug:
* Link to browser console log if relevant:
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):

**Comment by MattyBoombalatty** [comment]
Same issue here. People have to upload their own thumbnails for it to work.

**Comment by Chocobozzz** [comment]
Thanks for the details, the bug should be fixed by https://github.com/Chocobozzz/PeerTube/commit/1606e41195991c729718f9bfc76dc84eff72c83f

**Comment by tretkowski** [comment]
This is still an issue after upgrading to PeerTube 6.3.3, see https://peertube.netzbegruenung.de/c/jon_channel/videos as an example.

**Comment by Chocobozzz** [comment]
Can you check and paste your server logs?

**Comment by tretkowski** [comment]
Same error that @MattyBoombalatty posted here:

```
[peertube.netzbegruenung.de:443] 2024-11-26 20:27:48.507 error: Cannot copy/regenerate thumbnails of ended live b0c98cf5-e9bd-4d7e-ab3a-d42312fce44d to external video 5befad47-eb8d-4860-9120-9c7d38c3e5fa
```

**Comment by Chocobozzz** [comment]
Can you paste the link of your live?

**Comment by tretkowski** [comment]
https://peertube.netzbegruenung.de/w/cmspPRfLnTNW4ygFrWi2wA
