### ISSUE TITLE
Spacebar should still control playback after making the video fullscreen

### ISSUE THREAD

**Issue by MayeulC** [Chocobozzz/PeerTube#865]
* **PeerTube version or URL:** peertube.cpy.re
* **Browser name/version:** Firefox 61.01

* **What is the expected behaviour?**
After making a video fullscreen, I expect to be able to play/pause it using the spacebar.

* **What do you see instead?**
Hitting space instead leaves fullscreen, because clicking the button previously granted it focus.

I understand that it has to remain compatible with a tab-space workflow. So if someone selects the fullscreen control and presses space, that control should (that's open to debate) remain selected after entering fullscreen. However, there is no reason why clicking the control instead would select it *and* activate it.

I'm not sure what would be the best way to handle this. Maybe the event onclick callback could check if a key (space?) was pressed, and re-select the play button instead if it was not. Or as per [this](https://stackoverflow.com/questions/8735764/prevent-firing-focus-event-when-clicking-on-div):
```javascript
$(this).on('mousedown', function(event) {
// current function to make it fullscreen
event.preventDefault();});
```

I haven't looked at the current implementation, though.

**Comment by Chocobozzz** [comment]
I can't reproduce in the latest peertube, so I think this issue has been fixed.

**Comment by MayeulC** [comment]
@Chocobozzz  I can still reproduce on peertube.cpy.re (this should be running the latest version, right?). My browser is now Firefox 71.

1. Open a video
2. Click the fullscreen button
3. During playback, hit space to pause playback. It just closes the fullscreen window.

**Comment by Chocobozzz** [comment]
Could you test with https://peertube2.cpy.re/videos/watch/04af977f-4201-4697-be67-a8d8cae6fa7a please?

**Comment by nanawel** [comment]
Sorry to bump, but I had hoped this issue would be fixed in the latest release I've just deployed but it doesn't seem so.

Like @MayeulC said, you just have to open a video, then click the Fullscreen button, then press space and what it does is it exits the fullscreen mode, not pauses the playback as one would expect.

Is there some way to fix that already?

I'm using the latest Peertube Docker image
```
peertube_1  | > peertube@3.2.1 start /app
peertube_1  | > node dist/server
```
and I've tested with Firefox 89 and Chromium 91.

**Comment by frankstrater** [comment]
What happens is that when you click on the Fullscreen button, the button remains in focus and the spacebar press then acts like another onclick on this button instead of pausing the video. This also happens when using other buttons in the player, like Settings for instance.

**Comment by nanawel** [comment]
> What happens is that when you click on the Fullscreen button, the button remains in focus and the spacebar press then acts like another onclick on this button instead of pausing the video. This also happens when using other buttons in the player, like Settings for instance.

Yes I understand the cause and I figured it out already, but this is an annoying behavior IMHO.

Now that I see what consequences it can have for accessibility, I guess it might not be a bug but rather a feature we could turn on or off, on the whole instance or better, on a per account basis.

What do you think?

**Comment by frankstrater** [comment]
I think it's acceptable to "fix" this as described, because Enter/Return key is still an option to use for accessibility and is not yet taken in the larger set of Keyboard Shortcuts in PeerTube.

**Comment by MayeulC** [comment]
Supporting alternate shortcuts (and emphasizing that they exist) could also help.

I recently figured that youtube supports j/k/l to go backwards/pause/forward.

It's nice as a lot of layouts have these on the home row, and do not conflict with spacebar to select. Invidious also support these, and so does jellyfin for a few examples.

(youtube also supports dot "." to advance a frame, but that doesn't work on AZERTY keyboards...)
